# Change these first
owner: rodrigomorales77 # Your GitHub organization or username, where this repository lives
repo: aion # The name of this repository

sites:
  - name: CESPAL
    url: https://cespal.aion.com.ar
  - name: RUFINO
    url: https://rufino.aion.com.ar
  - name: AION
    url: https://aion.com.ar
  #- name: Test Broken Site
  #  url: https://thissitedoesnotexist.koj.co

assignees:
    - rodrigomorales77

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /aion
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AION Status Page
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a AION Status pages
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
